samplesheet: "./data/sampleSheet.csv"
outdir: "./data/results/"
experiment:
    name: "toy_data"
aggregation: false
scvi:
    n_latent: 10
    n_top_genes: 10
postprocessing:
    n_pca_components: 3
    n_diffmap_components: 3
    metadata: "None"
celltypist:
    model: "Immune_All_Low.pkl"
report:
    plots: "None"
mount: "/data1,/home,/scratch"
with_gpu: true
max_memory: "6.GB"
max_cpus: 6
maxForks: 2
