samplesheet: "./data/sampleSheet.csv"
outdir: "../scratch/"
experiment:
    name: "toy_data"
cellbender:
    total_droplets_included: 2000
scvi:
    n_latent: 10
    n_top_genes: 10
postprocessing:
    n_pca_components: 3
    n_diffmap_components: 3
    metadata: "None"
with_gpu: true
max_memory: "6.GB"
max_cpus: 6
maxForks: 2
